"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_createCollection(object):
    def setupUi(self, createCollection):
        createCollection.setObjectName("createCollection")
        createCollection.resize(500, 200)
        createCollection.setMinimumSize(QtCore.QSize(500, 200))
        createCollection.setMaximumSize(QtCore.QSize(500, 200))
        createCollection.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"}\n"
"\n"
"QLabel#errorLabel\n"
"{\n"
"    color: rgb(217, 174, 23);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(createCollection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(createCollection)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.collPathLine = QtWidgets.QLineEdit(createCollection)
        self.collPathLine.setObjectName("collPathLine")
        self.horizontalLayout.addWidget(self.collPathLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.errorLabel = QtWidgets.QLabel(createCollection)
        self.errorLabel.setStyleSheet("")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(createCollection)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(createCollection)
        self.buttonBox.accepted.connect(createCollection.accept) # type: ignore
        self.buttonBox.rejected.connect(createCollection.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(createCollection)

    def retranslateUi(self, createCollection):
        _translate = QtCore.QCoreApplication.translate
        createCollection.setWindowTitle(_translate("createCollection", "New Collection"))
        self.label.setText(_translate("createCollection", "iRODS path                                      /"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createCollection = QtWidgets.QDialog()
    ui = Ui_createCollection()
    ui.setupUi(createCollection)
    createCollection.show()
    sys.exit(app.exec())
