# Form implementation generated from reading ui file 'D:\Christine_irods\iBridges-Gui\gui\ui_files\dataTransferState.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dataTransferState(object):
    def setupUi(self, dataTransferState):
        dataTransferState.setObjectName("dataTransferState")
        dataTransferState.resize(443, 206)
        dataTransferState.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(dataTransferState)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(dataTransferState)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.cancelBtn = QtWidgets.QPushButton(self.groupBox)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout.addWidget(self.cancelBtn, 1, 3, 1, 1)
        self.confirmBtn = QtWidgets.QPushButton(self.groupBox)
        self.confirmBtn.setObjectName("confirmBtn")
        self.gridLayout.addWidget(self.confirmBtn, 1, 4, 1, 1)
        self.statusLbl = QtWidgets.QLabel(self.groupBox)
        self.statusLbl.setObjectName("statusLbl")
        self.gridLayout.addWidget(self.statusLbl, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 4, 0, 1, 4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadingLbl = QtWidgets.QLabel(dataTransferState)
        self.loadingLbl.setMinimumSize(QtCore.QSize(100, 100))
        self.loadingLbl.setText("")
        self.loadingLbl.setObjectName("loadingLbl")
        self.verticalLayout.addWidget(self.loadingLbl)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 2, 4, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.numDiffLabel = QtWidgets.QLabel(dataTransferState)
        self.numDiffLabel.setObjectName("numDiffLabel")
        self.horizontalLayout_2.addWidget(self.numDiffLabel)
        self.ChecksumLbl = QtWidgets.QLabel(dataTransferState)
        self.ChecksumLbl.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ChecksumLbl.setObjectName("ChecksumLbl")
        self.horizontalLayout_2.addWidget(self.ChecksumLbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ChecksumSizeLbl = QtWidgets.QLabel(dataTransferState)
        self.ChecksumSizeLbl.setObjectName("ChecksumSizeLbl")
        self.horizontalLayout_2.addWidget(self.ChecksumSizeLbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.numAddLabel = QtWidgets.QLabel(dataTransferState)
        self.numAddLabel.setObjectName("numAddLabel")
        self.horizontalLayout.addWidget(self.numAddLabel)
        self.newFiles = QtWidgets.QLabel(dataTransferState)
        self.newFiles.setObjectName("newFiles")
        self.horizontalLayout.addWidget(self.newFiles)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.newFSizeLbl = QtWidgets.QLabel(dataTransferState)
        self.newFSizeLbl.setObjectName("newFSizeLbl")
        self.horizontalLayout.addWidget(self.newFSizeLbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 2, 1)

        self.retranslateUi(dataTransferState)
        QtCore.QMetaObject.connectSlotsByName(dataTransferState)

    def retranslateUi(self, dataTransferState):
        _translate = QtCore.QCoreApplication.translate
        dataTransferState.setWindowTitle(_translate("dataTransferState", "Dialog"))
        self.cancelBtn.setText(_translate("dataTransferState", "Cancel"))
        self.confirmBtn.setText(_translate("dataTransferState", "Upload"))
        self.statusLbl.setText(_translate("dataTransferState", "Loading"))
        self.numDiffLabel.setText(_translate("dataTransferState", "0"))
        self.ChecksumLbl.setText(_translate("dataTransferState", "Items to update (overwrite)"))
        self.ChecksumSizeLbl.setText(_translate("dataTransferState", "0"))
        self.numAddLabel.setText(_translate("dataTransferState", "0"))
        self.newFiles.setText(_translate("dataTransferState", "New items   "))
        self.newFSizeLbl.setText(_translate("dataTransferState", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dataTransferState = QtWidgets.QDialog()
    ui = Ui_dataTransferState()
    ui.setupUi(dataTransferState)
    dataTransferState.show()
    sys.exit(app.exec())
