# Form implementation generated from reading ui file 'D:\Christine_irods\iBridges-Gui\gui\ui_files\irodsIndexPopup.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_irodsIndexPopup(object):
    def setupUi(self, irodsIndexPopup):
        irodsIndexPopup.setObjectName("irodsIndexPopup")
        irodsIndexPopup.resize(1000, 480)
        irodsIndexPopup.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTabWidget\n"
"{\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    background-color: rgb(58, 152, 112);\n"
"    color: rgb(54, 54, 54);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"background-color: rgb(85, 87, 83);\n"
"selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QLabel#indexLabel\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QLabel#collLabel\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QLabel#errorLabel\n"
"{\n"
"    color: rgb(217, 174, 23);\n"
"}\n"
"\n"
"QPushButton#closeButton\n"
"{\n"
"    background-color: rgb(54, 54, 54);\n"
"    color: rgb(58, 152, 112);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(irodsIndexPopup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(irodsIndexPopup)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_3.addItem(spacerItem)
        self.collLabel = QtWidgets.QLabel(self.tab_2)
        self.collLabel.setText("")
        self.collLabel.setObjectName("collLabel")
        self.verticalLayout_3.addWidget(self.collLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.dataObjectTable = QtWidgets.QTableWidget(self.tab_2)
        self.dataObjectTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.dataObjectTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.dataObjectTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.dataObjectTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.dataObjectTable.setObjectName("dataObjectTable")
        self.dataObjectTable.setColumnCount(4)
        self.dataObjectTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dataObjectTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataObjectTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataObjectTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataObjectTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.dataObjectTable)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.indexLabel = QtWidgets.QLabel(self.tab)
        self.indexLabel.setText("")
        self.indexLabel.setObjectName("indexLabel")
        self.verticalLayout_2.addWidget(self.indexLabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.extractButton = QtWidgets.QPushButton(irodsIndexPopup)
        self.extractButton.setObjectName("extractButton")
        self.horizontalLayout.addWidget(self.extractButton)
        self.closeButton = QtWidgets.QPushButton(irodsIndexPopup)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setDefault(True)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.errorLabel = QtWidgets.QLabel(irodsIndexPopup)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)

        self.retranslateUi(irodsIndexPopup)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(irodsIndexPopup)

    def retranslateUi(self, irodsIndexPopup):
        _translate = QtCore.QCoreApplication.translate
        irodsIndexPopup.setWindowTitle(_translate("irodsIndexPopup", "Form"))
        item = self.dataObjectTable.horizontalHeaderItem(0)
        item.setText(_translate("irodsIndexPopup", "Name"))
        item = self.dataObjectTable.horizontalHeaderItem(1)
        item.setText(_translate("irodsIndexPopup", "Owner"))
        item = self.dataObjectTable.horizontalHeaderItem(2)
        item.setText(_translate("irodsIndexPopup", "Size"))
        item = self.dataObjectTable.horizontalHeaderItem(3)
        item.setText(_translate("irodsIndexPopup", "Creation Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("irodsIndexPopup", "Data Objects"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("irodsIndexPopup", "JSON"))
        self.extractButton.setText(_translate("irodsIndexPopup", "Extract Selected"))
        self.closeButton.setText(_translate("irodsIndexPopup", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    irodsIndexPopup = QtWidgets.QWidget()
    ui = Ui_irodsIndexPopup()
    ui.setupUi(irodsIndexPopup)
    irodsIndexPopup.show()
    sys.exit(app.exec())
