# Form implementation generated from reading ui file 'gui/ui_files/tabAmberData.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabAmberData(object):
    def setupUi(self, tabAmberData):
        tabAmberData.setObjectName("tabAmberData")
        tabAmberData.resize(640, 532)
        tabAmberData.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTreeView\n"
"{\n"
"background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QLabel#createStatusLabel\n"
"{\n"
"color: rgb(217, 174, 23);\n"
"}\n"
"\n"
"QLabel#unpackStatusLabel\n"
"{\n"
"color: rgb(217, 174, 23);\n"
"}\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(tabAmberData)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(tabAmberData)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.irodsZoneLabel1 = QtWidgets.QLabel(tabAmberData)
        self.irodsZoneLabel1.setText("")
        self.irodsZoneLabel1.setObjectName("irodsZoneLabel1")
        self.verticalLayout_3.addWidget(self.irodsZoneLabel1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.irodsUploadTree = QtWidgets.QTreeView(tabAmberData)
        self.irodsUploadTree.setMinimumSize(QtCore.QSize(0, 150))
        self.irodsUploadTree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.irodsUploadTree.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.irodsUploadTree.setObjectName("irodsUploadTree")
        self.horizontalLayout.addWidget(self.irodsUploadTree)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(tabAmberData)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.compressRescButton = QtWidgets.QComboBox(tabAmberData)
        self.compressRescButton.setObjectName("compressRescButton")
        self.horizontalLayout_2.addWidget(self.compressRescButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.createButton = QtWidgets.QPushButton(tabAmberData)
        font = QtGui.QFont()
        font.setBold(True)
        self.createButton.setFont(font)
        self.createButton.setObjectName("createButton")
        self.verticalLayout.addWidget(self.createButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.jobSubmitLabel = QtWidgets.QLabel(tabAmberData)
        self.jobSubmitLabel.setStyleSheet("")
        self.jobSubmitLabel.setText("")
        self.jobSubmitLabel.setObjectName("jobSubmitLabel")
        self.verticalLayout_3.addWidget(self.jobSubmitLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(tabAmberData)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.irodsZoneLabel2 = QtWidgets.QLabel(tabAmberData)
        self.irodsZoneLabel2.setText("")
        self.irodsZoneLabel2.setObjectName("irodsZoneLabel2")
        self.verticalLayout_3.addWidget(self.irodsZoneLabel2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.irodsDownloadTree = QtWidgets.QTreeView(tabAmberData)
        self.irodsDownloadTree.setMinimumSize(QtCore.QSize(0, 150))
        self.irodsDownloadTree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.irodsDownloadTree.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.irodsDownloadTree.setObjectName("irodsDownloadTree")
        self.horizontalLayout_3.addWidget(self.irodsDownloadTree)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(tabAmberData)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.decompressRescButton = QtWidgets.QComboBox(tabAmberData)
        self.decompressRescButton.setObjectName("decompressRescButton")
        self.horizontalLayout_4.addWidget(self.decompressRescButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.unpackButton = QtWidgets.QPushButton(tabAmberData)
        font = QtGui.QFont()
        font.setBold(True)
        self.unpackButton.setFont(font)
        self.unpackButton.setObjectName("unpackButton")
        self.verticalLayout_2.addWidget(self.unpackButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.unpackStatusLabel = QtWidgets.QLabel(tabAmberData)
        self.unpackStatusLabel.setText("")
        self.unpackStatusLabel.setObjectName("unpackStatusLabel")
        self.verticalLayout_3.addWidget(self.unpackStatusLabel)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)

        self.retranslateUi(tabAmberData)
        QtCore.QMetaObject.connectSlotsByName(tabAmberData)

    def retranslateUi(self, tabAmberData):
        _translate = QtCore.QCoreApplication.translate
        tabAmberData.setWindowTitle(_translate("tabAmberData", "Form"))
        self.label_2.setText(_translate("tabAmberData", "Choose data to send to Amberscript:"))
        self.label.setText(_translate("tabAmberData", "Use Glossary"))
        self.createButton.setText(_translate("tabAmberData", "Upload"))
        self.label_3.setText(_translate("tabAmberData", "Download results from Amberscript"))
        self.label_4.setText(_translate("tabAmberData", "Choose job"))
        self.unpackButton.setText(_translate("tabAmberData", "Download"))
