# Form implementation generated from reading ui file 'D:\Christine_irods\iBridges-Gui\gui\ui_files\tabDataBundle.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabDataBundle(object):
    def setupUi(self, tabDataBundle):
        tabDataBundle.setObjectName("tabDataBundle")
        tabDataBundle.resize(640, 532)
        tabDataBundle.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTreeView\n"
"{\n"
"background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QLabel#createStatusLabel\n"
"{\n"
"color: rgb(217, 174, 23);\n"
"}\n"
"\n"
"QLabel#unpackStatusLabel\n"
"{\n"
"color: rgb(217, 174, 23);\n"
"}\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(tabDataBundle)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(tabDataBundle)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.irodsZoneLabel1 = QtWidgets.QLabel(tabDataBundle)
        self.irodsZoneLabel1.setText("")
        self.irodsZoneLabel1.setObjectName("irodsZoneLabel1")
        self.verticalLayout_3.addWidget(self.irodsZoneLabel1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.irodsCollectionTree = QtWidgets.QTreeView(tabDataBundle)
        self.irodsCollectionTree.setMinimumSize(QtCore.QSize(0, 150))
        self.irodsCollectionTree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.irodsCollectionTree.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.irodsCollectionTree.setObjectName("irodsCollectionTree")
        self.horizontalLayout.addWidget(self.irodsCollectionTree)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(tabDataBundle)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.compressRescButton = QtWidgets.QComboBox(tabDataBundle)
        self.compressRescButton.setObjectName("compressRescButton")
        self.horizontalLayout_2.addWidget(self.compressRescButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.compressCheckBox = QtWidgets.QCheckBox(tabDataBundle)
        self.compressCheckBox.setObjectName("compressCheckBox")
        self.verticalLayout.addWidget(self.compressCheckBox)
        self.removeCheckBox = QtWidgets.QCheckBox(tabDataBundle)
        self.removeCheckBox.setObjectName("removeCheckBox")
        self.verticalLayout.addWidget(self.removeCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.createButton = QtWidgets.QPushButton(tabDataBundle)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.createButton.setFont(font)
        self.createButton.setObjectName("createButton")
        self.verticalLayout.addWidget(self.createButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.createStatusLabel = QtWidgets.QLabel(tabDataBundle)
        self.createStatusLabel.setStyleSheet("")
        self.createStatusLabel.setText("")
        self.createStatusLabel.setObjectName("createStatusLabel")
        self.verticalLayout_3.addWidget(self.createStatusLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(tabDataBundle)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.irodsZoneLabel2 = QtWidgets.QLabel(tabDataBundle)
        self.irodsZoneLabel2.setText("")
        self.irodsZoneLabel2.setObjectName("irodsZoneLabel2")
        self.verticalLayout_3.addWidget(self.irodsZoneLabel2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.irodsCompressionTree = QtWidgets.QTreeView(tabDataBundle)
        self.irodsCompressionTree.setMinimumSize(QtCore.QSize(0, 150))
        self.irodsCompressionTree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.irodsCompressionTree.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.irodsCompressionTree.setObjectName("irodsCompressionTree")
        self.horizontalLayout_3.addWidget(self.irodsCompressionTree)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(tabDataBundle)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.decompressRescButton = QtWidgets.QComboBox(tabDataBundle)
        self.decompressRescButton.setObjectName("decompressRescButton")
        self.horizontalLayout_4.addWidget(self.decompressRescButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.indexButton = QtWidgets.QPushButton(tabDataBundle)
        self.indexButton.setObjectName("indexButton")
        self.verticalLayout_2.addWidget(self.indexButton)
        self.unpackButton = QtWidgets.QPushButton(tabDataBundle)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.unpackButton.setFont(font)
        self.unpackButton.setObjectName("unpackButton")
        self.verticalLayout_2.addWidget(self.unpackButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.unpackStatusLabel = QtWidgets.QLabel(tabDataBundle)
        self.unpackStatusLabel.setText("")
        self.unpackStatusLabel.setObjectName("unpackStatusLabel")
        self.verticalLayout_3.addWidget(self.unpackStatusLabel)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)

        self.retranslateUi(tabDataBundle)
        QtCore.QMetaObject.connectSlotsByName(tabDataBundle)

    def retranslateUi(self, tabDataBundle):
        _translate = QtCore.QCoreApplication.translate
        tabDataBundle.setWindowTitle(_translate("tabDataBundle", "Form"))
        self.label_2.setText(_translate("tabDataBundle", "Compress/Bundle Collections:"))
        self.label.setText(_translate("tabDataBundle", "Migrate data bundle to:"))
        self.compressCheckBox.setText(_translate("tabDataBundle", "Compress data"))
        self.removeCheckBox.setText(_translate("tabDataBundle", "Remove collection"))
        self.createButton.setText(_translate("tabDataBundle", "Create tar/zip"))
        self.label_3.setText(_translate("tabDataBundle", "Decompress tar/zip files:"))
        self.label_4.setText(_translate("tabDataBundle", "Migrate extracted data to:"))
        self.indexButton.setText(_translate("tabDataBundle", "Index"))
        self.unpackButton.setText(_translate("tabDataBundle", "Extract tar/zip"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabDataBundle = QtWidgets.QWidget()
    ui = Ui_tabDataBundle()
    ui.setupUi(tabDataBundle)
    tabDataBundle.show()
    sys.exit(app.exec())
