"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabELNData(object):
    def setupUi(self, tabELNData):
        tabELNData.setObjectName("tabELNData")
        tabELNData.resize(1234, 776)
        tabELNData.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTextBrowser\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTreeView\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QLineEdit#elnTokenInput\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"QLabel#errorLabel{\n"
"  \n"
"    color: rgb(217, 174, 23);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(tabELNData)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(tabELNData)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(tabELNData)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.elnTokenInput = QtWidgets.QLineEdit(tabELNData)
        self.elnTokenInput.setStyleSheet("")
        self.elnTokenInput.setObjectName("elnTokenInput")
        self.horizontalLayout_7.addWidget(self.elnTokenInput)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.elnGroupTable = QtWidgets.QTableWidget(tabELNData)
        self.elnGroupTable.setMinimumSize(QtCore.QSize(200, 200))
        self.elnGroupTable.setStyleSheet("")
        self.elnGroupTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.elnGroupTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.elnGroupTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.elnGroupTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.elnGroupTable.setObjectName("elnGroupTable")
        self.elnGroupTable.setColumnCount(2)
        self.elnGroupTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.elnGroupTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.elnGroupTable.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_8.addWidget(self.elnGroupTable)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.elnExperimentTable = QtWidgets.QTableWidget(tabELNData)
        self.elnExperimentTable.setMinimumSize(QtCore.QSize(400, 200))
        self.elnExperimentTable.setStyleSheet("")
        self.elnExperimentTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.elnExperimentTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.elnExperimentTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.elnExperimentTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.elnExperimentTable.setObjectName("elnExperimentTable")
        self.elnExperimentTable.setColumnCount(3)
        self.elnExperimentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.elnExperimentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.elnExperimentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.elnExperimentTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_8.addWidget(self.elnExperimentTable)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(tabELNData)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_14)
        self.groupIdLabel = QtWidgets.QLabel(tabELNData)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupIdLabel.setFont(font)
        self.groupIdLabel.setText("")
        self.groupIdLabel.setObjectName("groupIdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.groupIdLabel)
        self.label_15 = QtWidgets.QLabel(tabELNData)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_15)
        self.experimentIdLabel = QtWidgets.QLabel(tabELNData)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.experimentIdLabel.setFont(font)
        self.experimentIdLabel.setText("")
        self.experimentIdLabel.setObjectName("experimentIdLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.experimentIdLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.localFsTable = QtWidgets.QTreeView(tabELNData)
        self.localFsTable.setMinimumSize(QtCore.QSize(500, 0))
        self.localFsTable.setStyleSheet("")
        self.localFsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.localFsTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.localFsTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.localFsTable.setObjectName("localFsTable")
        self.horizontalLayout_9.addWidget(self.localFsTable)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.elnUploadButton = QtWidgets.QPushButton(tabELNData)
        self.elnUploadButton.setObjectName("elnUploadButton")
        self.horizontalLayout_9.addWidget(self.elnUploadButton)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.elnPathLabel = QtWidgets.QVBoxLayout()
        self.elnPathLabel.setObjectName("elnPathLabel")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(tabELNData)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.elnIrodsPath = QtWidgets.QLineEdit(tabELNData)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.elnIrodsPath.setFont(font)
        self.elnIrodsPath.setObjectName("elnIrodsPath")
        self.horizontalLayout_10.addWidget(self.elnIrodsPath)
        self.elnPathLabel.addLayout(self.horizontalLayout_10)
        self.elnPreviewBrowser = QtWidgets.QTextBrowser(tabELNData)
        self.elnPreviewBrowser.setMinimumSize(QtCore.QSize(0, 200))
        self.elnPreviewBrowser.setStyleSheet("")
        self.elnPreviewBrowser.setObjectName("elnPreviewBrowser")
        self.elnPathLabel.addWidget(self.elnPreviewBrowser)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.elnPathLabel.addItem(spacerItem5)
        self.horizontalLayout_9.addLayout(self.elnPathLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.errorLabel = QtWidgets.QLabel(tabELNData)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)

        self.retranslateUi(tabELNData)
        QtCore.QMetaObject.connectSlotsByName(tabELNData)

    def retranslateUi(self, tabELNData):
        _translate = QtCore.QCoreApplication.translate
        tabELNData.setWindowTitle(_translate("tabELNData", "Form"))
        self.label_9.setText(_translate("tabELNData", "Upload data to iRODS and link to an ELN Experiment"))
        self.label_12.setText(_translate("tabELNData", "ELN token (wur.elabjournal.com;12345)"))
        item = self.elnGroupTable.horizontalHeaderItem(0)
        item.setText(_translate("tabELNData", "Group ID"))
        item = self.elnGroupTable.horizontalHeaderItem(1)
        item.setText(_translate("tabELNData", "Group Name"))
        item = self.elnExperimentTable.horizontalHeaderItem(0)
        item.setText(_translate("tabELNData", "Experiment ID"))
        item = self.elnExperimentTable.horizontalHeaderItem(1)
        item.setText(_translate("tabELNData", "Experiment Name"))
        item = self.elnExperimentTable.horizontalHeaderItem(2)
        item.setText(_translate("tabELNData", "Owner Name"))
        self.label_14.setText(_translate("tabELNData", "Project"))
        self.label_15.setText(_translate("tabELNData", "Experiment"))
        self.elnUploadButton.setText(_translate("tabELNData", "Upload"))
        self.label_16.setText(_translate("tabELNData", "iRODS Path (adjust for YODA)"))
        self.elnIrodsPath.setText(_translate("tabELNData", "/zone/home/user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabELNData = QtWidgets.QWidget()
    ui = Ui_tabELNData()
    ui.setupUi(tabELNData)
    tabELNData.show()
    sys.exit(app.exec())
