"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabFederations(object):
    def setupUi(self, tabFederations):
        tabFederations.setObjectName("tabFederations")
        tabFederations.resize(1278, 754)
        tabFederations.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTreewidget\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(tabFederations)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(tabFederations)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.tableWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.treeWidget = QtWidgets.QTreeWidget(tabFederations)
        self.treeWidget.setStyleSheet("")
        self.treeWidget.setObjectName("treeWidget")
        self.horizontalLayout_5.addWidget(self.treeWidget)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton = QtWidgets.QPushButton(tabFederations)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(tabFederations)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.treeWidget_2 = QtWidgets.QTreeWidget(tabFederations)
        self.treeWidget_2.setStyleSheet("")
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.horizontalLayout_5.addWidget(self.treeWidget_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(tabFederations)
        QtCore.QMetaObject.connectSlotsByName(tabFederations)

    def retranslateUi(self, tabFederations):
        _translate = QtCore.QCoreApplication.translate
        tabFederations.setWindowTitle(_translate("tabFederations", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("tabFederations", "Federated Zones"))
        self.treeWidget.headerItem().setText(0, _translate("tabFederations", "Home iRODS"))
        self.treeWidget_2.headerItem().setText(0, _translate("tabFederations", "Federated iRODS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabFederations = QtWidgets.QWidget()
    ui = Ui_tabFederations()
    ui.setupUi(tabFederations)
    tabFederations.show()
    sys.exit(app.exec())
