"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabInfo(object):
    def setupUi(self, tabInfo):
        tabInfo.setObjectName("tabInfo")
        tabInfo.resize(640, 480)
        tabInfo.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTextBrowser\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(tabInfo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.serverLabel = QtWidgets.QLabel(tabInfo)
        self.serverLabel.setText("")
        self.serverLabel.setObjectName("serverLabel")
        self.gridLayout.addWidget(self.serverLabel, 13, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(tabInfo)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(tabInfo)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 15, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(tabInfo)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 13, 0, 1, 1)
        self.versionLabel_2 = QtWidgets.QLabel(tabInfo)
        self.versionLabel_2.setObjectName("versionLabel_2")
        self.gridLayout.addWidget(self.versionLabel_2, 14, 0, 1, 1)
        self.versionLabel = QtWidgets.QLabel(tabInfo)
        self.versionLabel.setText("")
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout.addWidget(self.versionLabel, 14, 2, 1, 1)
        self.groupsLabel = QtWidgets.QLabel(tabInfo)
        self.groupsLabel.setText("")
        self.groupsLabel.setObjectName("groupsLabel")
        self.gridLayout.addWidget(self.groupsLabel, 7, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 17, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(tabInfo)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(tabInfo)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(tabInfo)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.zoneLabel = QtWidgets.QLabel(tabInfo)
        self.zoneLabel.setText("")
        self.zoneLabel.setObjectName("zoneLabel")
        self.gridLayout.addWidget(self.zoneLabel, 3, 2, 1, 1)
        self.userLabel = QtWidgets.QLabel(tabInfo)
        self.userLabel.setText("")
        self.userLabel.setObjectName("userLabel")
        self.gridLayout.addWidget(self.userLabel, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 12, 0, 1, 1)
        self.typeLabel = QtWidgets.QLabel(tabInfo)
        self.typeLabel.setText("")
        self.typeLabel.setObjectName("typeLabel")
        self.gridLayout.addWidget(self.typeLabel, 5, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.refreshButton = QtWidgets.QPushButton(tabInfo)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_3.addWidget(self.refreshButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 18, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem6, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(tabInfo)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 16, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(tabInfo)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(tabInfo)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.rescTable = QtWidgets.QTableWidget(tabInfo)
        self.rescTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.rescTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.rescTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.rescTable.setObjectName("rescTable")
        self.rescTable.setColumnCount(3)
        self.rescTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rescTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rescTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rescTable.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.rescTable, 16, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(tabInfo)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.rescLabel = QtWidgets.QLabel(tabInfo)
        self.rescLabel.setText("")
        self.rescLabel.setObjectName("rescLabel")
        self.gridLayout.addWidget(self.rescLabel, 8, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)

        self.retranslateUi(tabInfo)
        QtCore.QMetaObject.connectSlotsByName(tabInfo)

    def retranslateUi(self, tabInfo):
        _translate = QtCore.QCoreApplication.translate
        tabInfo.setWindowTitle(_translate("tabInfo", "Form"))
        self.label_7.setText(_translate("tabInfo", "Server Information"))
        self.label_2.setText(_translate("tabInfo", "Server"))
        self.versionLabel_2.setText(_translate("tabInfo", "Version"))
        self.label_4.setText(_translate("tabInfo", "Username"))
        self.label.setText(_translate("tabInfo", "Client Information"))
        self.label_5.setText(_translate("tabInfo", "User\'s groups"))
        self.refreshButton.setText(_translate("tabInfo", "Refresh"))
        self.label_9.setText(_translate("tabInfo", "Resources"))
        self.label_3.setText(_translate("tabInfo", "Zone"))
        self.label_10.setText(_translate("tabInfo", "Usertype"))
        item = self.rescTable.horizontalHeaderItem(0)
        item.setText(_translate("tabInfo", "Name"))
        item = self.rescTable.horizontalHeaderItem(1)
        item.setText(_translate("tabInfo", "Free space [GB]"))
        item = self.rescTable.horizontalHeaderItem(2)
        item.setText(_translate("tabInfo", "Status"))
        self.label_8.setText(_translate("tabInfo", "Default resource"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabInfo = QtWidgets.QWidget()
    ui = Ui_tabInfo()
    ui.setupUi(tabInfo)
    tabInfo.show()
    sys.exit(app.exec())
