"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabticketCreate(object):
    def setupUi(self, tabticketCreate):
        tabticketCreate.setObjectName("tabticketCreate")
        tabticketCreate.resize(1021, 650)
        tabticketCreate.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QCalendarWidget\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTreeView{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QLabel#infoLabel{\n"
"    color: rgb(217, 174, 23);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(tabticketCreate)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(tabticketCreate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.createTicketButton = QtWidgets.QPushButton(tabticketCreate)
        self.createTicketButton.setObjectName("createTicketButton")
        self.gridLayout_2.addWidget(self.createTicketButton, 4, 0, 1, 1)
        self.calendar = QtWidgets.QCalendarWidget(tabticketCreate)
        self.calendar.setMinimumDate(QtCore.QDate(2020, 9, 14))
        self.calendar.setGridVisible(False)
        self.calendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendar.setObjectName("calendar")
        self.gridLayout_2.addWidget(self.calendar, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(tabticketCreate)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 6, 0, 1, 1)
        self.ticketInfoBrowser = QtWidgets.QTextBrowser(tabticketCreate)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.ticketInfoBrowser.setFont(font)
        self.ticketInfoBrowser.setObjectName("ticketInfoBrowser")
        self.gridLayout_2.addWidget(self.ticketInfoBrowser, 9, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_2.addItem(spacerItem3, 5, 0, 1, 1)
        self.infoLabel = QtWidgets.QLabel(tabticketCreate)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout_2.addWidget(self.infoLabel, 11, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_2.addLayout(self.formLayout, 8, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        self.irodsFsTreeView = QtWidgets.QTreeView(tabticketCreate)
        self.irodsFsTreeView.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.irodsFsTreeView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.irodsFsTreeView.setObjectName("irodsFsTreeView")
        self.gridLayout.addWidget(self.irodsFsTreeView, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(tabticketCreate)
        QtCore.QMetaObject.connectSlotsByName(tabticketCreate)

    def retranslateUi(self, tabticketCreate):
        _translate = QtCore.QCoreApplication.translate
        tabticketCreate.setWindowTitle(_translate("tabticketCreate", "Form"))
        self.label_2.setText(_translate("tabticketCreate", "Expiration date: (linux only)"))
        self.createTicketButton.setText(_translate("tabticketCreate", "Create Ticket"))
        self.label.setText(_translate("tabticketCreate", "Ticket Information: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabticketCreate = QtWidgets.QWidget()
    ui = Ui_tabticketCreate()
    ui.setupUi(tabticketCreate)
    tabticketCreate.show()
    sys.exit(app.exec())
