"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabTicketAccess(object):
    def setupUi(self, tabTicketAccess):
        tabTicketAccess.setObjectName("tabTicketAccess")
        tabTicketAccess.resize(943, 728)
        tabTicketAccess.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTreeView\n"
"{\n"
"  background-color: rgb(85, 87, 83);    \n"
"\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QLabel#infoLabel\n"
"{\n"
"    color: rgb(217, 174, 23);\n"
"}\n"
"\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(tabTicketAccess)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(tabTicketAccess)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.serverEdit = QtWidgets.QLineEdit(tabTicketAccess)
        self.serverEdit.setObjectName("serverEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.serverEdit)
        self.label_2 = QtWidgets.QLabel(tabTicketAccess)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.pathEdit = QtWidgets.QLineEdit(tabTicketAccess)
        self.pathEdit.setObjectName("pathEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pathEdit)
        self.label = QtWidgets.QLabel(tabTicketAccess)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.ticketEdit = QtWidgets.QLineEdit(tabTicketAccess)
        self.ticketEdit.setObjectName("ticketEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ticketEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connectButton = QtWidgets.QPushButton(tabTicketAccess)
        self.connectButton.setMinimumSize(QtCore.QSize(30, 30))
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.infoLabel = QtWidgets.QLabel(tabTicketAccess)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.homeButton = QtWidgets.QPushButton(tabTicketAccess)
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        if getattr(sys, "frozen", False):
            icon.addPixmap(QtGui.QPixmap("../gui/ui_files/../icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        else:
            icon.addPixmap(QtGui.QPixmap("gui/ui_files/../icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout_5.addWidget(self.homeButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.downloadAllButton = QtWidgets.QPushButton(tabTicketAccess)
        self.downloadAllButton.setObjectName("downloadAllButton")
        self.horizontalLayout_5.addWidget(self.downloadAllButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.collTable = QtWidgets.QTableWidget(tabTicketAccess)
        self.collTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.collTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.collTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.collTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.collTable.setObjectName("collTable")
        self.collTable.setColumnCount(5)
        self.collTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.collTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.collTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.collTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.collTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.collTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.collTable)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.downloadButton = QtWidgets.QPushButton(tabTicketAccess)
        self.downloadButton.setText("")
        icon1 = QtGui.QIcon()
        if getattr(sys, "frozen", False):
            icon1.addPixmap(QtGui.QPixmap("../gui/ui_files/../icons/arrow-right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        else:
            icon1.addPixmap(QtGui.QPixmap("gui/ui_files/../icons/arrow-right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.downloadButton.setIcon(icon1)
        self.downloadButton.setIconSize(QtCore.QSize(30, 30))
        self.downloadButton.setObjectName("downloadButton")
        self.verticalLayout_4.addWidget(self.downloadButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.createDirectoryButton = QtWidgets.QPushButton(tabTicketAccess)
        self.createDirectoryButton.setObjectName("createDirectoryButton")
        self.horizontalLayout_4.addWidget(self.createDirectoryButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.localFsTreeView = QtWidgets.QTreeView(tabTicketAccess)
        self.localFsTreeView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.localFsTreeView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.localFsTreeView.setObjectName("localFsTreeView")
        self.verticalLayout_5.addWidget(self.localFsTreeView)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem7)
        self.tabWidget = QtWidgets.QTabWidget(tabTicketAccess)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.previewBrowser = QtWidgets.QTextBrowser(self.tab)
        self.previewBrowser.setObjectName("previewBrowser")
        self.verticalLayout_3.addWidget(self.previewBrowser)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.metadataTable = QtWidgets.QTableWidget(self.tab_2)
        self.metadataTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.metadataTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.metadataTable.setObjectName("metadataTable")
        self.metadataTable.setColumnCount(3)
        self.metadataTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.metadataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.metadataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.metadataTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.metadataTable)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem8)

        self.retranslateUi(tabTicketAccess)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(tabTicketAccess)

    def retranslateUi(self, tabTicketAccess):
        _translate = QtCore.QCoreApplication.translate
        tabTicketAccess.setWindowTitle(_translate("tabTicketAccess", "Form"))
        self.label_3.setText(_translate("tabTicketAccess", "iRODS server: "))
        self.label_2.setText(_translate("tabTicketAccess", "iRODS path: "))
        self.label.setText(_translate("tabTicketAccess", "Ticket:"))
        self.connectButton.setText(_translate("tabTicketAccess", "Connect"))
        self.downloadAllButton.setText(_translate("tabTicketAccess", "Download all"))
        item = self.collTable.horizontalHeaderItem(0)
        item.setText(_translate("tabTicketAccess", "Path"))
        item = self.collTable.horizontalHeaderItem(1)
        item.setText(_translate("tabTicketAccess", "Name"))
        item = self.collTable.horizontalHeaderItem(2)
        item.setText(_translate("tabTicketAccess", "Size"))
        item = self.collTable.horizontalHeaderItem(3)
        item.setText(_translate("tabTicketAccess", "Checksum"))
        item = self.collTable.horizontalHeaderItem(4)
        item.setText(_translate("tabTicketAccess", "Last modified"))
        self.createDirectoryButton.setText(_translate("tabTicketAccess", "Create Directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("tabTicketAccess", "Preview"))
        item = self.metadataTable.horizontalHeaderItem(0)
        item.setText(_translate("tabTicketAccess", "Key"))
        item = self.metadataTable.horizontalHeaderItem(1)
        item.setText(_translate("tabTicketAccess", "Value"))
        item = self.metadataTable.horizontalHeaderItem(2)
        item.setText(_translate("tabTicketAccess", "Units"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("tabTicketAccess", "Metadata"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabTicketAccess = QtWidgets.QWidget()
    ui = Ui_tabTicketAccess()
    ui.setupUi(tabTicketAccess)
    tabTicketAccess.show()
    sys.exit(app.exec())
