"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabUpDownload(object):
    def setupUi(self, tabUpDownload):
        tabUpDownload.setObjectName("tabUpDownload")
        tabUpDownload.resize(1234, 720)
        tabUpDownload.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QGroupBox\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTreeView\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"\n"
"QPushButton#ContUplBut\n"
"{\n"
"    image : url(icons/nosync.png) stretch stretch;\n"
"}\n"
"\n"
"QRadioButton#uplAllRB, QRadioButton#uplMetaRB, QRadioButton#uplF500RB, QCheckBox#rLocalcopyCB, QCheckBox#saveSettings\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"QLabel#errorLabel\n"
"{\n"
"    color: rgb(217, 174, 23);\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(tabUpDownload)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1231, 771))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.createFolderButton = QtWidgets.QPushButton(self.layoutWidget)
        self.createFolderButton.setObjectName("createFolderButton")
        self.horizontalLayout_13.addWidget(self.createFolderButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.localFsTreeView = QtWidgets.QTreeView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localFsTreeView.sizePolicy().hasHeightForWidth())
        self.localFsTreeView.setSizePolicy(sizePolicy)
        self.localFsTreeView.setStyleSheet("")
        self.localFsTreeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.localFsTreeView.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.localFsTreeView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.localFsTreeView.setHeaderHidden(True)
        self.localFsTreeView.setObjectName("localFsTreeView")
        self.verticalLayout_5.addWidget(self.localFsTreeView)
        self.verticalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        self.resourceBox = QtWidgets.QComboBox(self.layoutWidget)
        self.resourceBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.resourceBox.setObjectName("resourceBox")
        self.resourceBox.addItem("")
        self.verticalLayout_15.addWidget(self.resourceBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.UploadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.UploadButton.setMinimumSize(QtCore.QSize(100, 0))
        self.UploadButton.setText("")
        icon = QtGui.QIcon()
        if getattr(sys, "frozen", False):
            icon.addPixmap(QtGui.QPixmap(r"../gui/ui_files/../icons/arrow-right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        else:
            icon.addPixmap(QtGui.QPixmap(r"gui/ui_files/../icons/arrow-right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.UploadButton.setIcon(icon)
        self.UploadButton.setIconSize(QtCore.QSize(50, 50))
        self.UploadButton.setObjectName("UploadButton")
        self.gridLayout_7.addWidget(self.UploadButton, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 2, 1, 1)
        self.DownloadButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DownloadButton.sizePolicy().hasHeightForWidth())
        self.DownloadButton.setSizePolicy(sizePolicy)
        self.DownloadButton.setMinimumSize(QtCore.QSize(100, 0))
        self.DownloadButton.setText("")
        icon1 = QtGui.QIcon()
        if getattr(sys, "frozen", False):
            icon1.addPixmap(QtGui.QPixmap(r"../gui/ui_files/../icons/arrow-left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        else:
            icon1.addPixmap(QtGui.QPixmap(r"gui/ui_files/../icons/arrow-left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.DownloadButton.setIcon(icon1)
        self.DownloadButton.setIconSize(QtCore.QSize(50, 50))
        self.DownloadButton.setObjectName("DownloadButton")
        self.gridLayout_7.addWidget(self.DownloadButton, 3, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_7.addItem(spacerItem6, 1, 1, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_16.addWidget(self.label_20)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.irodsZoneLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irodsZoneLabel.sizePolicy().hasHeightForWidth())
        self.irodsZoneLabel.setSizePolicy(sizePolicy)
        self.irodsZoneLabel.setObjectName("irodsZoneLabel")
        self.horizontalLayout_15.addWidget(self.irodsZoneLabel)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.createCollButton = QtWidgets.QPushButton(self.layoutWidget)
        self.createCollButton.setObjectName("createCollButton")
        self.horizontalLayout_15.addWidget(self.createCollButton)
        self.verticalLayout_16.addLayout(self.horizontalLayout_15)
        self.irodsFsTreeView = QtWidgets.QTreeView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irodsFsTreeView.sizePolicy().hasHeightForWidth())
        self.irodsFsTreeView.setSizePolicy(sizePolicy)
        self.irodsFsTreeView.setStyleSheet("")
        self.irodsFsTreeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.irodsFsTreeView.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.irodsFsTreeView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.irodsFsTreeView.setHeaderHidden(True)
        self.irodsFsTreeView.setObjectName("irodsFsTreeView")
        self.verticalLayout_16.addWidget(self.irodsFsTreeView)
        self.verticalLayout_16.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_16)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.logs = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.logs.setReadOnly(False)
        self.logs.setObjectName("logs")
        self.verticalLayout_11.addWidget(self.logs)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_11.addItem(spacerItem10)
        self.logs1 = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.logs1.setObjectName("logs1")
        self.verticalLayout_11.addWidget(self.logs1)
        self.errorLabel = QtWidgets.QLabel(self.layoutWidget)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout_11.addWidget(self.errorLabel)
        self.verticalLayout_11.setStretch(0, 2)

        self.retranslateUi(tabUpDownload)
        QtCore.QMetaObject.connectSlotsByName(tabUpDownload)

    def retranslateUi(self, tabUpDownload):
        _translate = QtCore.QCoreApplication.translate
        tabUpDownload.setWindowTitle(_translate("tabUpDownload", "Form"))
        self.label_19.setText(_translate("tabUpDownload", "LOCAL"))
        self.createFolderButton.setText(_translate("tabUpDownload", "Create Folder"))
        self.label_2.setText(_translate("tabUpDownload", "Select: resource / free GB"))
        self.resourceBox.setItemText(0, _translate("tabUpDownload", "Resources"))
        self.label_20.setText(_translate("tabUpDownload", "IRODS"))
        self.irodsZoneLabel.setText(_translate("tabUpDownload", "Zone"))
        self.createCollButton.setText(_translate("tabUpDownload", "Create Collection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabUpDownload = QtWidgets.QWidget()
    ui = Ui_tabUpDownload()
    ui.setupUi(tabUpDownload)
    tabUpDownload.show()
    sys.exit(app.exec())
