# iBridges CLI
The iBridges CLI is a command line interface to up and download large amounts of data. It only updates data when necessary, i.e. if checksums of files differ.

## Configuration

The client uses the same configuration files as the GUI, i.e. the *irods_environment.json* and the *ibridges_config.json*.

- Please create a directory named `.irods` in your home directory:
	- Linux: /home/\<username\>/.irods/irods_environment.json
	- Mac: /Users/\<username\>/.irods/irods_environment.json
	- Windows: C:\\\\....\\\<username\>\\.irods\\irods_environment.json	

- Please create a directory named `.ibridges` in your home directory

## Commandline parameters
- `--local_path LOCAL_PATH, -l LOCAL_PATH`: mandatory
- ` --irods_path IRODS_PATH, -i IRODS_PATH`: mandatory
- `--operation {upload,download}, -o {upload,download}`: mandatory, direction of data transfer
- `--env ENV, -e ENV`: optional, path to *irods_environment.json*; default value is last irods environment file as mentioned in *.ibridges/ibridges_conf.json*, if that value is not set in the file it is the default *.irods/irods_environment.json*
- `--irods_resc IRODS_RESC, -r IRODS_RESC`: optional, default should be set in *.irods/irods_environment.json* as `"irods_default_resource": "name of resource"`
- `--logdir LOGDIR`: optional, default is *.ibridges* in your home directory


## Usage

```sh
./iBridgesCli.py -h
usage: python iBridgesCli.py [-h] [--local_path LOCAL_PATH]
                             [--irods_path IRODS_PATH] --operation
                             {upload,download} [--env ENV]
                             [--irods_resc IRODS_RESC] [--logdir LOGDIR]

options:
  -h, --help            show this help message and exit
  --local_path LOCAL_PATH, -l LOCAL_PATH
                        Local path to download to, or upload from
  --irods_path IRODS_PATH, -i IRODS_PATH
                        iRods path to upload to, or download from
  --operation {upload,download}, -o {upload,download}
  --env ENV, -e ENV     Path to iRods environment file
                        (irods_environment.json).
  --irods_resc IRODS_RESC, -r IRODS_RESC
                        iRods resource. If omitted default will be read from
                        iRods env file.
  --logdir LOGDIR       Directory for logfile. Default:
                        /home/user/.ibridges
```
