---
title: "What is iBridges"
---
iBridges is a standalone client software *desktop application*, written in **Python**, to provide users of *Windows, Linux and Mac* with a *graphical user interface* to interact with **iRODS** servers. 
The tool is agnostic to any rules/policies in the server. The out-of-the-box iBridges supports three main functions: browsing and manipulating data objects, upload/download data, and search through data collections. 

We also provide a command line interface with which data can be uploaded and downloaded.

The GUI can be extended by users to implement their own data workflows.

### Current views/features

- `tabBrowser`: (Default) a main table to browse through collections, metadata and ACL manipulation, data deletion and single file up and downloads,
- `tabUpDownload`: a two-pane upload/download tab
- `tabELNData`: Uploading data and linking it to an Electronical Labnotebook experiment
- `tabAmberWorkflow`: Up ad downloading data to and from Amberscript from iRODS
- `tabDataBundle`: (un)bundle datasets from/to four supported formats (depending on extra iRODS microservices)
- `tabCreateTicket`: create iRODS tickets for anonymous access
-  `tabInfo`: (Default) an overview over the iRODS server and client, groups and resources
- The search functionality is available from the drop-down menu `Options` 
- Login with ticket: (Experimental)

## Dependencies
- Python3.9+
- QT v6+

## Authors
Maintainer: Christine Staiger, Tim van Daalen

Contributors: John McFarland, Maarten Schermer, Simona Stoica, Jos Tersteeg

## License
GPL v3
